// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/shopify": {
    params: {};
  };
  "/shopify/login": {
    params: {};
  };
  "/shopify/webhook-test": {
    params: {};
  };
  "/shopify/callback": {
    params: {};
  };
  "/shopify/dashboard": {
    params: {};
  };
  "/shopify/api/token": {
    params: {};
  };
  "/shopify/api/products": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/shopify" | "/shopify/login" | "/shopify/webhook-test" | "/shopify/callback" | "/shopify/dashboard" | "/shopify/api/token" | "/shopify/api/products";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/shopify/index.tsx": {
    id: "routes/shopify/index";
    page: "/shopify";
  };
  "routes/shopify/login.tsx": {
    id: "routes/shopify/login";
    page: "/shopify/login";
  };
  "routes/shopify/webhook-test.tsx": {
    id: "routes/shopify/webhook-test";
    page: "/shopify/webhook-test";
  };
  "routes/shopify/callback.tsx": {
    id: "routes/shopify/callback";
    page: "/shopify/callback";
  };
  "routes/shopify/dashboard.tsx": {
    id: "routes/shopify/dashboard";
    page: "/shopify/dashboard";
  };
  "routes/shopify/api/token.tsx": {
    id: "routes/shopify/api/token";
    page: "/shopify/api/token";
  };
  "routes/shopify/api/products.tsx": {
    id: "routes/shopify/api/products";
    page: "/shopify/api/products";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/shopify/index": typeof import("./app/routes/shopify/index.tsx");
  "routes/shopify/login": typeof import("./app/routes/shopify/login.tsx");
  "routes/shopify/webhook-test": typeof import("./app/routes/shopify/webhook-test.tsx");
  "routes/shopify/callback": typeof import("./app/routes/shopify/callback.tsx");
  "routes/shopify/dashboard": typeof import("./app/routes/shopify/dashboard.tsx");
  "routes/shopify/api/token": typeof import("./app/routes/shopify/api/token.tsx");
  "routes/shopify/api/products": typeof import("./app/routes/shopify/api/products.tsx");
};